version: '2'
services:
  cesweb-kernel-quartz:
    build: 
      context: .
    image: cesweb-kernel-quartz:1.0.0
    restart: always
    ports:
      - 5100:5100
    networks:
      - server_net
    external_links:
      - server-redis:redis
    environment:
      REDIS_HOST: redis
networks:
  server_net:
    external: true
        
    