version: '3.7'
services:
  # redis服务
  redis:
    image: redis
    container_name: server-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - default
      - server_net
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
      - "./redis/data:/data"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    command: redis-server --appendonly yes
  
  # mysql数据库
  mysql:
    image: mysql
    container_name: server-mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - default
      - server_net
    volumes:
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root@123
    command: --default-authentication-plugin=mysql_native_password

  # nginx反向代理
  nginx:
    image: nginx
    container_name: server-nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    networks:
      - default
      - server_net
    volumes:
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf/conf.d/:/etc/nginx/conf.d/"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/log:/var/log/nginx"
      - "/data/secret/cert:/etc/cert"
      - type: bind
        source: ./nginx/shared/trust-certificates
        target: /harbor_cust_cert
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    
networks:
  server_net:
    external: true