server:
  port: 5020
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      cookie:
        name: sentinel_dashboard_cookie
      
logging:
  file: ${user.home}/logs/csp/sentinel-dashboard.log
  level:
    org:
      springframework:
        web: INFO
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
      
auth:
  filter:
    exclude-url-suffixes: htm,html,js,css,map,ico,ttf,woff,png
    exclude-urls: /,/auth/login,/auth/logout,/registry/machine,/version
  password: sentinel
  username: sentinel
    
sentinel:
  dashboard:
    version: 1.7.2
    

